language: python
python:
- '2.7'

before_install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls

install:
    - python setup.py install

script:
    - python setup.py develop
    - nosetests --with-coverage --cover-package=cloudshell

after_success:
    coveralls
